# .github/workflows/daily-commit.yml
name: Daily Commit

# allow both schedule runs and manual triggers
on:
  schedule:
    - cron: '0 0 * * *'    # every day at 00:00 UTC (change as needed)
  workflow_dispatch: {}   # enables “Run workflow” button

permissions:
  contents: write         # give the job permission to push commits

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # ensures checkout supplies the token to push

      - name: Append timestamp by 24f2001127@ds.study.iitm.ac.in
        run: |
          echo "Automated commit at $(date -u +"%Y-%m-%d %H:%M:%SZ")" >> daily_commit.log

      - name: Commit changes by 24f2001127@ds.study.iitm.ac.in
        run: |
          git config user.name "24f2001127@ds.study.iitm.ac.in"
          git config user.email "24f2001127@ds.study.iitm.ac.in"
          git add daily_commit.log
          git commit -m "chore: daily automated commit"
          git push
