# .github/workflows/daily-commit.yml
name: Daily Commit

on:
  schedule:
    # runs daily at midnight UTC; change the time fields (min hour) as desired
    - cron: '0 0 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Append timestamp by 24f2001127@ds.study.iitm.ac.in
        run: |
          echo "Automated commit at $(date -u +"%Y-%m-%d %H:%M:%SZ")" >> daily_commit.log

      - name: Commit changes by 24f2001127@ds.study.iitm.ac.in
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily_commit.log
          git commit -m "chore: daily automated commit"
          git push
          echo "Commit pushed!"
